const assert=require('node:assert/strict');require('../data.js');require('../engine.js');
const I=globalThis.Irish,vs=globalThis.IRISH_DATA.verbs;
const f=(l,t,p='Sg1',s='pos')=>I.forms(vs.find(v=>v.lemma===l),t,p,s);
assert.equal(vs.length,61);assert.equal(vs.filter(v=>v.irregular).length,11);
const fixtures=[['bí','Past','Sg1','pos','bhí mé'],['bí','Past','Sg1','neg','ní raibh mé'],['bí','Pres','Sg1','neg','nílim'],['bí','Pres','Sg2','q','an bhfuil tú'],['abair','Past','Sg1','neg','ní dúirt mé'],['abair','Fut','Sg1','q','an ndéarfaidh mé'],['déan','Past','Sg2','q','an ndearna tú'],['faigh','Past','Sg1','neg','ní bhfuair mé'],['faigh','Fut','Sg1','pos','gheobhaidh mé'],['faigh','Fut','Sg1','neg','ní bhfaighidh mé'],['feic','Past','Sg2','q','an bhfaca tú'],['téigh','Past','Sg1','neg','ní dheachaigh mé'],['ith','Past','Sg1','pos',"d'ith mé"],['ith','Past','Sg1','q','ar ith mé'],['ól','PresCont','Sg1','nq','nach n-ólaim'],['fág','Past','Sg1','pos',"d'fhág mé"],['bris','Past','Auto','pos','briseadh'],['clois','Past','Auto','pos','chualathas'],['tar','Past','Auto','pos','thángthas'],['bí','Imper','Sg2','neg','ná bí'],['ith','Imper','Sg2','neg','ná hith'],['bí','Subj','Sg2','pos','go raibh tú'],['bí','Subj','Sg2','neg','ná raibh tú'],['scríobh','ProgPres','Sg1','pos','táim ag scríobh'],['scríobh','PerfPast','Sg1','pos','bhí mé tar éis scríobh'],['bí','PerfPres','Sg1','pos','táim tar éis a bheith'],['ceannaigh','Fut','Pl1','pos','ceannóimid'],['oscail','Cond','Sg1','pos',"d'osclóinn"],['bí','PastSubj','Sg1','pos','dá mbeinn']];
for(const [l,t,p,s,want]of fixtures)assert.ok(f(l,t,p,s).includes(want),`${l} ${t} ${p} ${s}: ${f(l,t,p,s)} expected ${want}`);
let cards=0;for(const v of vs)for(const t of Object.keys(I.tenses))for(const p of Object.keys(I.persons))for(const s of Object.keys(I.shapes)){const a=I.forms(v,t,p,s);for(const x of a){assert.ok(x.trim());assert.ok(!/undefined|null|  |\[object/.test(x),x);assert.equal(I.check(x,a),'correct');}if(a.length){cards++;assert.ok(!/undefined|null/.test(I.english(v,t,p,s)));assert.ok(!/undefined|null/.test(I.example(v,t,p,s,a[0])));}}
for(const v of vs)for(const t of ['PresCont','Past','PastCont','Fut','Cond','Imper','Subj','PastSubj'])for(const p of Object.keys(I.persons))for(const s of ['pos','neg'])assert.ok(I.forms(v,t,p,s).length,`Missing ${v.lemma} ${t} ${p} ${s}`);
assert.equal(I.check('D’ith   mé?', ["d'ith mé"]),'correct');assert.equal(I.check('bhi me',['bhí mé']),'accent');assert.equal(I.check('bhi me',['bhí mé'],false),'correct-accent');assert.equal(I.check('bhí tú',['bhí mé']),'incorrect');
console.log(`${fixtures.length} linguistic fixtures passed; ${cards} cards validated; complete finite person/tense coverage.`);
