(function(){
'use strict';
const $=id=>document.getElementById(id),I=Irish,verbs=IRISH_DATA.verbs,KEY='briathra-progress-v1';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let saved={version:1,attempts:0,correct:0,mistakes:[]},storageOK=true;
try{const raw=localStorage.getItem(KEY);if(raw)saved=validate(JSON.parse(raw));}catch(e){storageOK=false;}
let bank=[],session=[],index=0,right=0,answered=false,current=null,reviewing=false;
function validate(x){
 if(!x||x.version!==1||!Number.isInteger(x.attempts)||!Number.isInteger(x.correct)||x.correct<0||x.attempts<x.correct||!Array.isArray(x.mistakes)||x.mistakes.length>60000)throw Error('Invalid progress file');
 const mistakes=[...new Set(x.mistakes)];for(const k of mistakes){if(typeof k!=='string')throw Error('Invalid card');const [l,t,p,s]=k.split('|');const v=verbs.find(v=>v.lemma===l);if(!v||!I.tenses[t]||!I.persons[p]||!I.shapes[s]||!I.forms(v,t,p,s).length)throw Error('Unknown card in progress file');}
 return {version:1,attempts:x.attempts,correct:x.correct,mistakes};
}
function save(){try{localStorage.setItem(KEY,JSON.stringify(saved));storageOK=true;}catch(e){storageOK=false;}stats();}
function stats(){ $('mistakeCount').textContent=saved.mistakes.length;$('review').disabled=!saved.mistakes.length;$('storageStatus').textContent=(storageOK?'Saved in this browser. ':'Browser storage unavailable; export to keep your progress. ')+`${saved.correct} / ${saved.attempts} correct overall.`;}
function options(id,items){$(id).innerHTML=items.map(([key,label])=>`<label><input type="checkbox" value="${esc(key)}"> <span>${esc(label)}</span></label>`).join('');}
options('verbOptions',verbs.map(v=>[v.lemma,`${v.lemma} · ${v.en}${v.irregular?' ★':''}`]));options('tenseOptions',Object.entries(I.tenses));options('personOptions',Object.entries(I.persons));options('shapeOptions',Object.entries(I.shapes));
function selected(id){return [...$(id).querySelectorAll('input:checked')].map(x=>x.value);}
function choose(id,fn){$(id).querySelectorAll('input').forEach(x=>x.checked=fn(x.value));}
function selection(){return {vs:selected('verbOptions'),ts:selected('tenseOptions'),ps:selected('personOptions'),ss:selected('shapeOptions')};}
function makeBank(){const {vs,ts,ps,ss}=selection();let result=[];for(const v of verbs.filter(v=>vs.includes(v.lemma)))for(const t of ts)for(const p of (t==='VN'||t==='VA'?['Sg1']:ps))for(const s of (t==='VN'||t==='VA'?['pos']:ss)){let a=I.forms(v,t,p,s);if(a.length)result.push({v,t,p,s,a,key:[v.lemma,t,p,s].join('|')});}return result;}
function update(){bank=makeBank();$('verbCount').textContent=selected('verbOptions').length+'/61';$('tenseCount').textContent=selected('tenseOptions').length;$('poolStatus').textContent=bank.length.toLocaleString()+' available practice cards. '+(bank.length?'Filters apply to the next new session.':'Select compatible verbs, tenses, persons and sentence types.');$('start').disabled=!bank.length;}
function preset(name){choose('verbOptions',l=>name==='core'?verbs.find(v=>v.lemma===l).irregular:name==='regular'?!verbs.find(v=>v.lemma===l).irregular:true);choose('tenseOptions',t=>name==='all'?['PresCont','Pres','Past','PastCont','Fut','Cond','Imper','Subj','PastSubj'].includes(t):name==='compound'?t.startsWith('Prog')||t.startsWith('Perf'):['PresCont','Past','Fut'].includes(t));choose('personOptions',p=>name==='all'||p!=='Auto');choose('shapeOptions',s=>name==='all'||s==='pos'||s==='q');update();}
function shuffle(a){a=[...a];for(let j=a.length-1;j>0;j--){const k=Math.floor(Math.random()*(j+1));[a[j],a[k]]=[a[k],a[j]];}return a;}
function fromKey(k){const [l,t,p,s]=k.split('|'),v=verbs.find(v=>v.lemma===l);return {v,t,p,s,a:I.forms(v,t,p,s),key:k};}
function start(review=false){reviewing=review;let pool=review?saved.mistakes.map(fromKey):bank;session=shuffle(pool).slice(0,$('length').value==='all'?pool.length:Number($('length').value));index=right=0;if(session.length)show();}
function show(){
 $('feedback').innerHTML='';$('progress').max=session.length;$('progress').value=index;
 $('sessionLabel').textContent=(reviewing?'REVIEW':'PRACTICE')+` · ${Math.min(index+1,session.length)} / ${session.length}`;$('score').textContent=right+' correct';
 if(index>=session.length){current=null;$('answerForm').hidden=true;$('question').innerHTML=`<p class="tag">Session complete</p><h2>${right} out of ${session.length}.</h2><p>${right===session.length?'Excellent work. Try another tense or a wider set of verbs.':'Keep going, little by little. Review saved mistakes when you’re ready.'}</p><p class="muted">Choose “Start a new session” for another shuffled round.</p>`;return;}
 current=session[index];answered=false;const {v,t,p,s}=current;
 const nonfinite=t==='VN'||t==='VA';const tail=t.startsWith('Prog')||t.startsWith('Perf')?v.vnTail:v.tail;
 $('question').innerHTML=`<p class="tag">${esc(I.tenses[t])} · ${esc(I.shapes[s])}</p><h2 lang="ga">${esc(v.lemma)} <span class="muted">— ${esc(v.en)}</span></h2><p class="prompt">${esc(I.english(v,t,p,s))}</p>${nonfinite?'':`<p lang="ga" class="cloze">[________] [${esc(tail)}]${t==='PastSubj'?', [bheadh sé go maith].':s==='q'||s==='nq'?'?':'.'}</p>`}<p class="muted">${nonfinite?'Enter the nonfinite form.':esc(I.persons[p])+' · Fill the entire first bracket, including particles and pronouns.'}</p>`;
 $('answerForm').hidden=false;$('answer').value='';$('answer').disabled=false;$('check').hidden=false;$('reveal').hidden=false;$('next').hidden=true;$('answer').focus();
}
function grade(reveal=false){if(!current||answered)return;let value=$('answer').value;if(!reveal&&!value.trim()){$('answer').focus();return;}
 const {v,t,p,s,a,key}=current,result=reveal?'revealed':I.check(value,a,$('strict').checked),ok=result==='correct'||result==='correct-accent';answered=true;saved.attempts++;if(ok){right++;saved.correct++;saved.mistakes=saved.mistakes.filter(k=>k!==key);}else if(!saved.mistakes.includes(key))saved.mistakes.push(key);save();
 let title=ok?(result==='correct-accent'?'Accepted — check the fadas below.':'Correct. Maith thú!'):result==='accent'?'Almost — check the fadas.':reveal?'Here is the answer.':'A form to practise again.';
 $('feedback').innerHTML=`<h3 class="${ok?'success':'error'}">${esc(title)}</h3><p class="answer" lang="ga">${a.map(esc).join(' <span class="muted">or</span> ')}</p><p lang="ga">${esc(I.example(v,t,p,s,a[0]))}</p><p class="muted">${esc(explanation(t,p,s))}</p><p class="muted">Lemma pronunciation: ${esc(v.pronunciation)} (approximate). <a href="https://www.teanglann.ie/en/fuaim/${encodeURIComponent(v.lemma)}" target="_blank" rel="noopener">Dialect recordings ↗</a></p>`;
 $('score').textContent=right+' correct';$('progress').value=index+1;$('answer').disabled=true;$('check').hidden=true;$('reveal').hidden=true;$('next').hidden=false;$('next').textContent=index+1===session.length?'Finish session →':'Next →';$('next').focus();
}
function explanation(t,p,s){let text=({Past:'The past often uses lenition and d’ before a vowel or f; irregular verbs may use a different dependent form.',PastCont:'The habitual past means “used to”. Several persons have endings that include the subject.',Fut:'The future expresses what will happen.',Cond:'The conditional means “would”. Its personal endings may already include the subject.',PresCont:'The simple present commonly describes habits. Bí has bíonn for habits and tá for a current state.',Pres:'Bí uses tá in affirmative statements, níl in negatives and bhfuil after an/nach.',Imper:'The imperative expresses commands or requests. The negative particle is ná.',Subj:'Go introduces an affirmative wish and causes eclipsis. Negative wishes normally use nár; bí uses ná.',PastSubj:'Dá / mura introduces a hypothetical condition and eclipses the dependent habitual-past form; bí instead uses mbeinn, mbeifeá, etc.',VN:'The verbal noun is used in constructions such as ag + verbal noun.',VA:'The verbal adjective is a nonfinite form. Its use depends on the verb and context.'})[t]||'This construction uses an inflected form of bí with '+(t.startsWith('Prog')?'ag':'tar éis')+' and a verbal noun.';if(p==='Auto')text+=' The autonomous form leaves the agent unspecified; do not add a subject pronoun.';return text;}
function reference(){const v=verbs.find(v=>v.lemma===$('referenceVerb').value),t=$('referenceTense').value;
 $('verbInfo').innerHTML=`<p><b lang="ga">${esc(v.lemma)}</b> · ${esc(v.en)} · ${v.irregular?'Irregular':'Regular'}</p><p class="muted">Verbal noun: <span lang="ga">${v.vn.map(esc).join(' / ')||'—'}</span> · Verbal adjective: <span lang="ga">${v.va.map(esc).join(' / ')||'not supplied'}</span><br>Approximate lemma pronunciation: ${esc(v.pronunciation)} · <a href="https://www.teanglann.ie/en/gram/${encodeURIComponent(v.lemma)}" target="_blank" rel="noopener">Dictionary ↗</a></p>`;
 const nonfinite=t==='VN'||t==='VA';let rows='';for(const p of nonfinite?['Sg1']:Object.keys(I.persons)){let cells='';for(const s of nonfinite?['pos']:Object.keys(I.shapes)){const a=I.forms(v,t,p,s);cells+=`<td lang="ga">${a.length?a.map(esc).join('<br>')+'<small>'+esc(I.example(v,t,p,s,a[0]))+'</small>':'<span class="muted">—</span>'}</td>`;}rows+=`<tr><th>${nonfinite?'Nonfinite form':esc(I.persons[p])}</th>${cells}</tr>`;}
 $('table').innerHTML=`<p class="muted">${esc(explanation(t,'',''))} A dash means this combination is not applicable or is not supplied.</p><table><thead><tr><th>Person</th>${(nonfinite?['pos']:Object.keys(I.shapes)).map(s=>'<th>'+esc(I.shapes[s])+'</th>').join('')}</tr></thead><tbody>${rows}</tbody></table>`;
}
$('referenceVerb').innerHTML=verbs.map(v=>`<option value="${esc(v.lemma)}">${esc(v.lemma)} · ${esc(v.en)}</option>`).join('');$('referenceTense').innerHTML=Object.entries(I.tenses).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('');
$('referenceVerb').onchange=reference;$('referenceTense').onchange=reference;
$('preset').onchange=()=>preset($('preset').value);
for(const id of ['verbOptions','tenseOptions','personOptions','shapeOptions'])$(id).onchange=update;
for(const [id,fn]of [['allVerbs',()=>true],['noVerbs',()=>false],['irregularVerbs',l=>verbs.find(v=>v.lemma===l).irregular],['regularVerbs',l=>!verbs.find(v=>v.lemma===l).irregular]])$(id).onclick=()=>{choose('verbOptions',fn);update();};
$('allTenses').onclick=()=>{choose('tenseOptions',()=>true);update();};$('noTenses').onclick=()=>{choose('tenseOptions',()=>false);update();};
$('verbSearch').oninput=()=>{const q=I.normalize($('verbSearch').value,true);$('verbOptions').querySelectorAll('label').forEach(l=>l.hidden=!I.normalize(l.textContent,true).includes(q));};
$('start').onclick=()=>start();$('review').onclick=()=>start(true);$('answerForm').onsubmit=e=>{e.preventDefault();grade();};$('reveal').onclick=()=>grade(true);$('next').onclick=()=>{index++;show();};
document.querySelector('.fadas').innerHTML=[...'áéíóú'].map(a=>`<button type="button" aria-label="Insert ${a}">${a}</button>`).join('');document.querySelectorAll('.fadas button').forEach(b=>b.onclick=()=>{const a=$('answer');if(a.disabled)return;const start=a.selectionStart,end=a.selectionEnd;a.value=a.value.slice(0,start)+b.textContent+a.value.slice(end);a.focus();a.setSelectionRange(start+1,start+1);});
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.hidden=x.id!==b.dataset.tab);document.querySelectorAll('nav button').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-current',x===b?'page':'false');});if(b.dataset.tab==='reference')reference();});
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(saved,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='briathra-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onchange=async()=>{const f=$('import').files[0];if(!f)return;try{if(f.size>5e6)throw Error('File too large');const incoming=validate(JSON.parse(await f.text()));saved={version:1,attempts:Math.max(saved.attempts,incoming.attempts),correct:Math.max(saved.correct,incoming.correct),mistakes:[...new Set([...saved.mistakes,...incoming.mistakes])]};save();$('storageStatus').textContent+=' Progress imported; mistake lists merged.';}catch(e){$('storageStatus').textContent='Could not import: '+e.message;}$('import').value='';};
$('reset').onclick=()=>{if(confirm('Clear all saved scores and mistakes?')){saved={version:1,attempts:0,correct:0,mistakes:[]};save();}};
preset('core');stats();reference();
})();
