const $=s=>document.querySelector(s), preps=window.PREPOSITIONS, persons=window.PERSONS;
const state={current:null,answered:false,total:0,correct:0,streak:0,history:JSON.parse(localStorage.getItem('reamhfhocail-progress')||'{}')};
const norm=s=>s.trim().toLocaleLowerCase('ga').replace(/[’‘]/g,"'").replace(/\s+/g,' ');
const plain=s=>norm(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function save(){localStorage.setItem('reamhfhocail-progress',JSON.stringify(state.history))}
function pool(){let list=[];preps.forEach((p,pi)=>p.forms.forEach((f,fi)=>list.push({p,pi,fi,f,key:`${p.base}:${fi}`})));const filter=$('#prepFilter').value;if(filter!=='all')list=list.filter(x=>x.p.base===filter);if($('#weakOnly').checked){const weak=list.filter(x=>(state.history[x.key]?.wrong||0)>=(state.history[x.key]?.right||0));if(weak.length)list=weak}return list}
function choose(){const list=pool();const weighted=list.flatMap(x=>Array(1+Math.min(4,state.history[x.key]?.wrong||0)).fill(x));let q=weighted[Math.floor(Math.random()*weighted.length)];let mode=$('#mode').value;if(mode==='mixed')mode=['form','sentence','meaning'][Math.floor(Math.random()*3)];q={...q,mode};state.current=q;state.answered=false;renderQuestion()}
function renderQuestion(){const q=state.current,p=q.p,person=persons[q.fi],pair=p.examples[q.fi].split('|');$('#prepBadge').textContent=p.base;$('#feedback').hidden=true;$('#feedback').className='feedback';$('#nextBtn').hidden=true;$('#hintBtn').hidden=false;$('#answer').value='';$('#answer').disabled=false;$('#answerForm button').disabled=false;if(q.mode==='form'){$('#questionKind').textContent='English → Irish form';$('#prompt').textContent=`${p.meaning} ${person.en}`;$('#context').textContent=`Use the preposition “${p.base}”.`}else if(q.mode==='sentence'){let sentence=pair[0].replace(q.f,'_____');$('#questionKind').textContent='Complete the sentence';$('#prompt').textContent=sentence;$('#context').textContent=pair[1]}else{$('#questionKind').textContent='Irish → English meaning';$('#prompt').textContent=q.f;$('#context').textContent=`Which person does this form refer to? (e.g. “me”, “her”, “them”)`}setTimeout(()=>$('#answer').focus(),20)}
function expected(q){return q.mode==='meaning'?persons[q.fi].en.split(' / '):[q.f]}
function check(e){e.preventDefault();if(state.answered){choose();return}const q=state.current,ans=norm($('#answer').value);if(!ans)return;const choices=expected(q);const exact=choices.some(x=>norm(x)===ans);const noFada=q.mode!=='meaning'&&choices.some(x=>plain(x)===plain(ans));const ok=exact||noFada;state.answered=true;state.total++;if(ok){state.correct++;state.streak++;state.history[q.key]={...(state.history[q.key]||{}),right:(state.history[q.key]?.right||0)+1}}else{state.streak=0;state.history[q.key]={...(state.history[q.key]||{}),wrong:(state.history[q.key]?.wrong||0)+1}}save();showFeedback(ok,noFada);updateStats();$('#answer').disabled=true;$('#answerForm button').disabled=true;$('#hintBtn').hidden=true;$('#nextBtn').hidden=false;$('#nextBtn').focus()}
function showFeedback(ok,noFada){const q=state.current,pair=q.p.examples[q.fi].split('|'),f=$('#feedback');f.hidden=false;f.classList.add(ok?'good':'bad');const answer=q.mode==='meaning'?persons[q.fi].en:q.f;f.innerHTML=`<strong>${ok?(noFada?'Correct — add the fada':'Ceart!'):'Not quite — '+answer}</strong><span>${pair[0]} — ${pair[1]}</span><br><span class="pronunciation">Approx. pronunciation: ${q.p.pron[q.fi]}</span>`}
function hint(){const q=state.current;const clue=q.mode==='meaning'?`It refers to “${persons[q.fi].ga}”.`:`Starts with “${q.f[0]}” and has ${[...q.f].length} letters.`;const f=$('#feedback');f.hidden=false;f.className='feedback';f.innerHTML=`<strong>Hint</strong>${clue}`}
function updateStats(){const reviewed=Object.values(state.history).filter(v=>(v.wrong||0)>=(v.right||0)&&(v.wrong||0)>0).length;$('#score').textContent=state.total?Math.round(state.correct/state.total*100)+'%':'0%';$('#streak').textContent=state.streak;$('#reviewCount').textContent=reviewed;$('#progress').value=state.total%20}
function buildReference(){const heads=persons.map(x=>`<th>${x.ga}</th>`).join('');const rows=preps.map((p,i)=>`<tr><th>${p.base}<br><small>${p.meaning}</small></th>${p.forms.map((f,j)=>`<td><button data-detail="${i}-${j}">${f}</button></td>`).join('')}</tr>`).join('');$('#referenceContent').innerHTML=`<div class="table-wrap"><table><thead><tr><th>prep.</th>${heads}</tr></thead><tbody>${rows}</tbody></table></div><div id="formDetail"></div>`;$('#referenceContent').addEventListener('click',e=>{const id=e.target.dataset.detail;if(!id)return;const [i,j]=id.split('-').map(Number),p=preps[i],pair=p.examples[j].split('|');$('#formDetail').innerHTML=`<table><tr class="detail-row"><td><strong>${p.forms[j]}</strong> · <span class="pronunciation">${p.pron[j]}</span><br>${pair[0]}<br>${pair[1]}</td></tr></table>`})}
preps.forEach(p=>$('#prepFilter').insertAdjacentHTML('beforeend',`<option value="${p.base}">${p.base} — ${p.meaning}</option>`));
$('#answerForm').addEventListener('submit',check);$('#nextBtn').addEventListener('click',choose);$('#hintBtn').addEventListener('click',hint);['prepFilter','mode','weakOnly'].forEach(id=>$('#'+id).addEventListener('change',choose));$('#referenceBtn').onclick=()=>$('#referenceDialog').showModal();$('#closeReference').onclick=()=>$('#referenceDialog').close();$('#referenceDialog').addEventListener('click',e=>{if(e.target===$('#referenceDialog'))e.target.close()});$('#resetBtn').onclick=()=>{if(confirm('Reset all saved practice history?')){state.history={};state.total=state.correct=state.streak=0;save();updateStats();choose()}};
buildReference();updateStats();choose();
