window.PREPOSITIONS = [
 {base:"ag",meaning:"at / by / have",forms:["agam","agat","aige","aici","againn","agaibh","acu"],pron:["ug-um","ug-ut","eg-eh","ak-ee","ug-in","ug-iv","uh-ku"],examples:["Tá peann agam.|I have a pen.","An bhfuil am agat?|Do you (singular) have time?","Tá carr aige.|He has a car.","Tá ceist aici.|She has a question.","Tá obair againn.|We have work.","Tá ticéid agaibh.|You (plural) have tickets.","Tá teach acu.|They have a house."]},
 {base:"ar",meaning:"on",forms:["orm","ort","air","uirthi","orainn","oraibh","orthu"],pron:["orum","ort","er","ur-hee","or-in","or-iv","or-hu"],examples:["Tá áthas orm.|I am happy.","Tá cóta ort.|You (singular) are wearing a coat.","Tá ocras air.|He is hungry.","Tá eagla uirthi.|She is afraid.","Tá deifir orainn.|We are in a hurry.","Tá an locht oraibh.|You (plural) are to blame.","Tá tart orthu.|They are thirsty."]},
 {base:"as",meaning:"out of / from",forms:["asam","asat","as","aisti","asainn","asaibh","astu"],pron:["as-um","as-ut","as","ash-tee","as-in","as-iv","as-tu"],examples:["Bhain sé geit asam.|He startled me.","Bhain sí gáire asat.|She made you (singular) laugh.","Bainfidh mé freagra as.|I will get an answer from him.","Bhain siad eolas aisti.|They got information from her.","Bhain sé anáil asainn.|It took our breath away.","Bhain siad sult asaibh.|They got amusement from you (plural).","Bain triail astu.|Try them."]},
 {base:"chuig",meaning:"to / towards",forms:["chugam","chugat","chuige","chuici","chugainn","chugaibh","chucu"],pron:["hug-um","hug-ut","hig-eh","hik-ee","hug-in","hug-iv","hu-ku"],examples:["Tar chugam.|Come to me.","Cuirfidh mé chugat é.|I will send it to you (singular).","Chuaigh mé chuige.|I went to him.","Rith sí chuici.|She ran to her.","Tá siad ag teacht chugainn.|They are coming to us.","Tiocfaidh sé chugaibh.|He will come to you (plural).","Chuaigh muid chucu.|We went to them."]},
 {base:"de",meaning:"off / of",forms:["díom","díot","de","di","dínn","díbh","díobh"],pron:["deem","deet","deh","dee","deen","deev","dee-uv"],examples:["Bhain mé mo chóta díom.|I took off my coat.","Bain díot do bhróga.|Take off your (singular) shoes.","Cad a cheapann tú de?|What do you think of him?","Níor bhain sé a shúile di.|He did not take his eyes off her.","Rinne sé dearmad dínn.|He forgot about us.","Tá mé bródúil díbh.|I am proud of you (plural).","Tá cuid díobh anseo.|Some of them are here."]},
 {base:"do",meaning:"to / for",forms:["dom","duit","dó","di","dúinn","daoibh","dóibh"],pron:["dum","ditch","doh","dee","doon","deev","doh-iv"],examples:["Tabhair dom é.|Give it to me.","Scríobh mé duit.|I wrote to you (singular).","Cheannaigh sí bronntanas dó.|She bought him a present.","Dúirt mé an fhírinne di.|I told her the truth.","Rinne sé tae dúinn.|He made tea for us.","Seo daoibh é.|Here it is for you (plural).","Thug sí bia dóibh.|She gave them food."]},
 {base:"faoi",meaning:"under / about",forms:["fúm","fút","faoi","fúithi","fúinn","fúibh","fúthu"],pron:["foom","foot","fwee","foo-hee","foo-in","foo-iv","foo-hu"],examples:["Tá an pluid fúm.|The blanket is under me.","Chuala mé scéal fút.|I heard a story about you (singular).","Labhair muid faoi.|We spoke about him.","Tá imní orm fúithi.|I am worried about her.","Bhí siad ag caint fúinn.|They were talking about us.","Cad a dúirt sé fúibh?|What did he say about you?","Rinneadh scannán fúthu.|A film was made about them."]},
 {base:"i",meaning:"in",forms:["ionam","ionat","ann","inti","ionainn","ionaibh","iontu"],pron:["un-um","un-ut","own","in-chee","un-in","un-iv","un-tu"],examples:["Tá dóchas ionam.|There is hope in me.","Tá ceol ionat.|You have music in you.","Tá sé ann.|He is there.","Tá misneach inti.|There is courage in her.","Tá neart ionainn.|There is strength in us.","Creidim ionaibh.|I believe in you (plural).","Tá siad iontu.|They are in them."]},
 {base:"le",meaning:"with / by",forms:["liom","leat","leis","léi","linn","libh","leo"],pron:["lum","lat","lesh","lay","lin","liv","lyoh"],examples:["Tar liom.|Come with me.","Aontaím leat.|I agree with you (singular).","Chuaigh sí leis.|She went with him.","Labhair mé léi.|I spoke with her.","Fan linn.|Stay with us.","Tá mé sásta libh.|I am pleased with you (plural).","D'imigh sé leo.|He left with them."]},
 {base:"ó",meaning:"from",forms:["uaim","uait","uaidh","uaithi","uainn","uaibh","uathu"],pron:["oo-im","oo-it","oo-ig","oo-hee","oo-in","oo-iv","oo-hu"],examples:["Cad atá uait uaim?|What do you (singular) want from me?","Fuair mé litir uait.|I got a letter from you (singular).","Fuair sí glaoch uaidh.|She got a call from him.","Cheannaigh mé é uaithi.|I bought it from her.","D'imigh sé uainn.|He left us.","Teastaíonn cabhair uaibh.|You (plural) need help.","Fuair muid nuacht uathu.|We got news from them."]},
 {base:"roimh",meaning:"before / in front of",forms:["romham","romhat","roimhe","roimpi","romhainn","romhaibh","rompu"],pron:["roh-um","roh-ut","roh-veh","rom-pee","roh-in","roh-iv","rom-pu"],examples:["Bhí bóthar fada romham.|A long road was ahead of me.","Tá rogha romhat.|You (singular) have a choice before you (singular).","Rith an madra roimhe.|The dog ran ahead of him.","Sheas sé roimpi.|He stood in front of her.","Tá dúshlán romhainn.|A challenge lies ahead of us.","Tá lá gnóthach romhaibh.|A busy day is ahead of you (plural).","Shiúil sí rompu.|She walked ahead of them."]},
 {base:"thar",meaning:"over / past",forms:["tharam","tharat","thairis","thairsti","tharainn","tharaibh","tharstu"],pron:["har-um","har-ut","har-ish","harsh-tee","har-in","har-iv","har-stu"],examples:["Léim sé tharam.|He jumped over me.","Chuaigh sí tharat.|She went past you (singular).","Chuaigh mé thairis.|I went past him.","Léim an cat thairsti.|The cat jumped over her.","D'eitil sé tharainn.|It flew over us.","Chuaigh an bus tharaibh.|The bus went past you (plural).","Léim sé tharstu.|He jumped over them."]},
 {base:"trí",meaning:"through",forms:["tríom","tríot","tríd","tríthi","trínn","tríbh","tríothu"],pron:["treem","treet","treed","tree-hee","treen","treev","tree-hu"],examples:["Chuaigh fuacht tríom.|A chill went through me.","Feicim tríot.|I see through you (singular).","Shiúil muid tríd.|We walked through it.","Chuaigh an tsnáthaid tríthi.|The needle went through her.","Shéid an ghaoth trínn.|The wind blew through us.","Rith an scéal tríbh.|The story spread through you (plural).","Chuaigh muid tríothu.|We went through them."]},
 {base:"um",meaning:"about / around",forms:["umam","umat","uime","uimpi","umainn","umaibh","umpu"],pron:["um-um","um-ut","im-eh","im-pee","um-in","um-iv","um-pu"],examples:["Chuir mé cóta umam.|I put a coat around me.","Cuir brat umat.|Put a blanket around you (singular).","Tá crios uime.|He has a belt around him.","Chuir sí seál uimpi.|She put a shawl around her.","Tá daoine umainn.|There are people around us.","Chuir siad fáinne umaibh.|They formed a ring around you (plural).","Bhailigh slua umpu.|A crowd gathered around them."]}
];
window.PERSONS=[{ga:"mé",en:"me / I"},{ga:"tú",en:"you (singular)"},{ga:"sé",en:"him / he"},{ga:"sí",en:"her / she"},{ga:"muid",en:"us / we"},{ga:"sibh",en:"you (plural)"},{ga:"siad",en:"them / they"}];
